# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
+ data source: http://jsonstudio.com/resources/
****

In [ ]:
import pandas as pd

## imports for Python, Pandas

In [ ]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [ ]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [ ]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

In [ ]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank 
+ data source: http://jsonstudio.com/resources/

In [ ]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

In [ ]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

In [1]:
# import packages needed
import pandas as pd
import json
from pandas.io.json import json_normalize

In [2]:
# load json, save as string
json = json.load((open('data/world_bank_projects.json')))

In [3]:
# normalize json into dataframe
json_df = json_normalize(json)
json_df.head()

,_id.$oid,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,source,status,supplementprojectflg,theme1.Name,theme1.Percent,theme_namecode,themecode,totalamt,totalcommamt,url
0,52b213b38594d8a2be17c780,1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,IBRD,Active,N,Education for all,100,"[{'code': '65', 'name': 'Education for all'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,52b213b38594d8a2be17c781,2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,IBRD,Active,N,Other economic management,30,"[{'code': '24', 'name': 'Other economic manage...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,52b213b38594d8a2be17c782,2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,IBRD,Active,Y,Regional integration,46,"[{'code': '47', 'name': 'Regional integration'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,52b213b38594d8a2be17c783,2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,IBRD,Active,N,Participation and civic engagement,50,"[{'code': '57', 'name': 'Participation and civ...","59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,52b213b38594d8a2be17c784,2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,IBRD,Active,N,Export development and competitiveness,30,"[{'code': '45', 'name': 'Export development an...","41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...

In [4]:
# group by country and run count on number of entries
json_df.groupby('country_namecode')['country_namecode'].count().sort_values(ascending=False)

country_namecode
People's Republic of China!$!CN                  19
Republic of Indonesia!$!ID                       19
Socialist Republic of Vietnam!$!VN               17
Republic of India!$!IN                           16
Republic of Yemen!$!RY                           13
Nepal!$!NP                                       12
People's Republic of Bangladesh!$!BD             12
Kingdom of Morocco!$!MA                          12
Africa!$!3A                                      11
Republic of Mozambique!$!MZ                      11
Burkina Faso!$!BF                                 9
Federative Republic of Brazil!$!BR                9
Islamic Republic of Pakistan!$!PK                 9
United Republic of Tanzania!$!TZ                  8
Republic of Tajikistan!$!TJ                       8
Republic of Armenia!$!AM                          8
Kyrgyz Republic!$!KG                              7
Lao People's Democratic Republic!$!LA             7
Hashemite Kingdom of Jordan!$!JO                  7
Federal Republic of Nigeria!$!NG                  7
Republic of Nicaragua!$!NI                        6
West Bank and Gaza!$!GZ                           6
Republic of Kenya!$!KE                            6
Islamic State of Afghanistan!$!AF                 6
Republic of Peru!$!PE                             6
Democratic Republic of the Congo!$!ZR             6
Republic of Niger!$!NE                            5
Republic of Moldova!$!MD                          5
Republic of Honduras!$!HN                         5
Republic of Haiti!$!HT                            5
                                                 ..
Republic of Seychelles!$!SC                       2
Plurinational State of Bolivia!$!BO               2
Republic of Sierra Leone!$!SL                     2
Republic of Ecuador!$!EC                          2
Argentine Republic!$!AR                           2
Republic of Cameroon!$!CM                         2
Arab Republic of Egypt!$!EG                       2
Tuvalu!$!TV                                       1
Antigua and Barbuda!$!AG                          1
Central African Republic!$!CF                     1
Europe and Central Asia!$!7E                      1
Democratic Socialist Republic of Sri Lan!$!LK     1
Bosnia and Herzegovina!$!BA                       1
East Asia and Pacific!$!4E                        1
Republic of Chile!$!CL                            1
Republic of Kiribati!$!KI                         1
Republic of Namibia!$!NA                          1
Romania!$!RO                                      1
Republic of Panama!$!PA                           1
Republic of Chad!$!TD                             1
Kingdom of Thailand!$!TH                          1
Kingdom of Tonga!$!TO                             1
Republic of Serbia!$!YF                           1
Republic of Zimbabwe!$!ZW                         1
People's Republic of Angola!$!AO                  1
Republic of Costa Rica!$!CR                       1
Republic of Congo!$!CG                            1
Republic of Belarus!$!BY                          1
Republic of Cape Verde!$!CV                       1
Republic of Poland!$!PL                           1
Name: country_namecode, Length: 118, dtype: int64

****

## Country Project Count

After normalizing the data and taking a count of the number of project entries for each country, the top 10 countries are:
1. China - 19
2. Indonesia - 19
3. Vietnam - 17
4. India - 16
5. Yemen - 13
6. Nepal - 12
7. Bangladesh - 12
8. Morocco - 12
9. Africa - 11
10. Mozambique - 11

The one result that is suspect is the entry for "Africa". Below, we can look at rows with "Africa" as a 'countryname' to see what countries within Africa this entry is referring to.

In [5]:
# explore what entries are listed under "Africa"
json_df[json_df['countryname']=='Africa']

,_id.$oid,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,source,status,supplementprojectflg,theme1.Name,theme1.Percent,theme_namecode,themecode,totalamt,totalcommamt,url
45,52b213b38594d8a2be17c7ad,2014,September,2013-09-12T00:00:00Z,ECOWAS,NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Health system performance,100,"[{'code': '67', 'name': 'Health system perform...",67,0,10000000,http://www.worldbank.org/projects/P125018/west...
46,52b213b38594d8a2be17c7ae,2014,September,2013-09-10T00:00:00Z,UGANDA-COMOROS,2018-06-30T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Administrative and civil service reform,20,"[{'code': '25', 'name': 'Administrative and ci...","39,40,78,25",22000000,22000000,http://www.worldbank.org/projects/P118213/rcip...
51,52b213b38594d8a2be17c7b3,2014,September,2013-09-04T00:00:00Z,"OSS, IUCN, CILSS",NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Biodiversity,20,"[{'code': '80', 'name': 'Biodiversity'}, {'cod...","85,82,81,83,80",0,4630000,http://www.worldbank.org/projects/P130888/buil...
58,52b213b38594d8a2be17c7ba,2014,August,2013-08-28T00:00:00Z,BANK EXECUTED,NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Biodiversity,50,"[{'code': '80', 'name': 'Biodiversity'}, {'cod...","82,80",0,2000000,http://www.worldbank.org/projects/P144902?lang=en
65,52b213b38594d8a2be17c7c1,2014,August,2013-08-06T00:00:00Z,"BURUNDI,RWANDA,TANZANIA",2020-12-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Infrastructure services for private sector dev...,15,"[{'code': '39', 'name': 'Infrastructure servic...","47,79,62,39",339900000,339900000,http://www.worldbank.org/projects/P075941/nels...
99,52b213b38594d8a2be17c7e3,2013,June,2013-06-28T00:00:00Z,GOVERNMENT OF MALI,NaN,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,Y,Regional integration,25,"[{'code': '47', 'name': 'Regional integration'...","78,27,48,47",60000000,60000000,http://www.worldbank.org/projects/P145160/addi...
167,52b213b38594d8a2be17c827,2013,May,2013-05-30T00:00:00Z,MINISTRIES OF TELECOM AND ICT,2018-11-30T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Regional integration,25,"[{'code': '47', 'name': 'Regional integration'...","48,40,39,47",60000000,60000000,http://www.worldbank.org/projects/P123093/west...
184,52b213b38594d8a2be17c838,2013,May,2013-05-21T00:00:00Z,TANZANIA,2018-12-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Regional integration,23,"[{'code': '47', 'name': 'Regional integration'...","88,74,49,47",213000000,213000000,http://www.worldbank.org/projects/P120370/sout...
287,52b213b38594d8a2be17c89f,2013,March,2013-03-14T00:00:00Z,"MALAWI, MOZAMBIQUE, ZAMBIA",2020-01-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Rural services and infrastructure,80,"[{'code': '78', 'name': 'Rural services and in...","47,48,78",90000000,90000000,http://www.worldbank.org/projects/P094183/agri...
353,52b213b38594d8a2be17c8e1,2013,January,2013-01-01T00:00:00Z,NILE BASIN INITIATIVE,2015-12-31T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Water resource management,74,"[{'code': '85', 'name': 'Water resource manage...","82,57,85",0,15300000,http://www.worldbank.org/projects/P130694/nile...
449,52b213b38594d8a2be17c941,2013,October,2012-10-02T00:00:00Z,GOVERNMENT OF NIGER,2020-04-01T00:00:00Z,Africa!$!3A,3A,Africa,Africa,...,IBRD,Active,N,Municipal governance and institution building,10,"[{'code': '73', 'name': 'Municipal governance ...","47,78,85,73",203000000,203000000,http://www.worldbank.org/projects/P130174/firs...

****

## Country Project Count (cont.)

Under the 'borrower' column, it looks like there are a number of different groups that have projects, such as the Government of Mali, Tanzania, Niger, and others. If we revise our Top 10 to include this fact, then we have:

1. China - 19
2. Indonesia - 19
3. Vietnam - 17
4. India - 16
5. Yemen - 13
6. Nepal - 12
7. Bangladesh - 12
8. Morocco - 12
9. Mozambique - 11
10. Burkina Faso - 9

In [6]:
# check the project theme namecodes
themes = json_normalize(json, 'mjtheme_namecode')
themes

     code                                          name
0       8                             Human development
1      11
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8
18     10                             Rural development
19      7
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5
1482    6         Social protection and risk management
1483    8
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [7]:
# notice that one of the entries is ''
themes['name'].unique()

array(['Human development', '', 'Economic management',
       'Social protection and risk management', 'Trade and integration',
       'Public sector governance',
       'Environment and natural resources management',
       'Social dev/gender/inclusion',
       'Financial and private sector development', 'Rural development',
       'Urban development', 'Rule of law'], dtype=object)

In [8]:
# create dict for code:name
theme_dict = {'1':'Economic management', 
              '2':'Public sector governance', 
              '3':'Rule of law', 
              '4':'Financial and private sector development', 
              '5':'Trade and integration', 
              '6':'Social protection and risk management', 
              '7':'Social dev/gender/inclusion', 
              '8':'Human development', 
              '9':'Urban development', 
              '10':'Rural development', 
              '11':'Environmental and natural resources management'}

In [9]:
# make 'name' column a duplicate of 'code', and then use .replace() based on dict
themes['name'] = themes['code']
themes['name'].replace(theme_dict, inplace=True)
themes

     code                                            name
0       8                               Human development
1      11  Environmental and natural resources management
2       1                             Economic management
3       6           Social protection and risk management
4       5                           Trade and integration
5       2                        Public sector governance
6      11  Environmental and natural resources management
7       6           Social protection and risk management
8       7                     Social dev/gender/inclusion
9       7                     Social dev/gender/inclusion
10      5                           Trade and integration
11      4        Financial and private sector development
12      6           Social protection and risk management
13      6           Social protection and risk management
14      2                        Public sector governance
15      4        Financial and private sector development
16     11  Environmental and natural resources management
17      8                               Human development
18     10                               Rural development
19      7                     Social dev/gender/inclusion
20      2                        Public sector governance
21      2                        Public sector governance
22      2                        Public sector governance
23     10                               Rural development
24      2                        Public sector governance
25     10                               Rural development
26      6           Social protection and risk management
27      6           Social protection and risk management
28     11  Environmental and natural resources management
29      4        Financial and private sector development
...   ...                                             ...
1469    8                               Human development
1470    9                               Urban development
1471    6           Social protection and risk management
1472    6           Social protection and risk management
1473    9                               Urban development
1474    2                        Public sector governance
1475    2                        Public sector governance
1476   10                               Rural development
1477   11  Environmental and natural resources management
1478    8                               Human development
1479    7                     Social dev/gender/inclusion
1480   11  Environmental and natural resources management
1481    5                           Trade and integration
1482    6           Social protection and risk management
1483    8                               Human development
1484    4        Financial and private sector development
1485    7                     Social dev/gender/inclusion
1486    8                               Human development
1487    5                           Trade and integration
1488    2                        Public sector governance
1489    8                               Human development
1490   10                               Rural development
1491    6           Social protection and risk management
1492   10                               Rural development
1493   10                               Rural development
1494   10                               Rural development
1495    9                               Urban development
1496    8                               Human development
1497    5                           Trade and integration
1498    4        Financial and private sector development

[1499 rows x 2 columns]

In [10]:
# now can check groupby to see which projects have the highest count
themes.groupby('name')['name'].count().sort_values(ascending=False)

name
Environmental and natural resources management    250
Rural development                                 216
Human development                                 210
Public sector governance                          199
Social protection and risk management             168
Financial and private sector development          146
Social dev/gender/inclusion                       130
Trade and integration                              77
Urban development                                  50
Economic management                                38
Rule of law                                        15
Name: name, dtype: int64

**** 

## Project Theme Count

As it turns out, there are only 11 unique themes, which means the Top 10 will be all but one. They are:

1. Environmental and natural resources management - 250
2. Rural development - 216
3. Human development - 210
4. Public sector governance - 199
5. Social protection and risk management - 168
6. Financial and private sector development - 146
7. Social dev/gender/inclusion - 130
8. Trade and integration - 77
9. Urban development - 50
10. Economic management - 38